
import Foundation

class GuideViewModel: ObservableObject {
    
    let dayLists: [Int: [Item]] = [
        1: [
            Item(id: UUID().uuidString, name: "Water Bottle", quantity: "1", category: .food),
            Item(id: UUID().uuidString, name: "ID Card", quantity: "1", category: .documents)
        ],
        2: [
            Item(id: UUID().uuidString, name: "Shampoo", quantity: "2 Bottles", category: .hygiene),
            Item(id: UUID().uuidString, name: "Deodorant Spray", quantity: "1 Can", category: .hygiene),
            Item(id: UUID().uuidString, name: "Toothbrush", quantity: "1", category: .hygiene),
            Item(id: UUID().uuidString, name: "Toothpaste", quantity: "1 Tube", category: .hygiene),
            Item(id: UUID().uuidString, name: "Tissues", quantity: "1 Pack", category: .hygiene),
        ],
        3: [
            Item(id: UUID().uuidString, name: "Shampoo", quantity: "3 Bottles", category: .hygiene),
            Item(id: UUID().uuidString, name: "Deodorant Spray", quantity: "2 Cans", category: .hygiene),
            Item(id: UUID().uuidString, name: "Toothbrush", quantity: "1", category: .hygiene),
            Item(id: UUID().uuidString, name: "Toothpaste", quantity: "2 Tubes", category: .hygiene),
            Item(id: UUID().uuidString, name: "Tissues", quantity: "2 Packs", category: .hygiene),
        ],
        4: [
            Item(id: UUID().uuidString, name: "Shampoo", quantity: "1 Bottle", category: .hygiene),
            Item(id: UUID().uuidString, name: "Deodorant Spray", quantity: "1 Can", category: .hygiene),
            Item(id: UUID().uuidString, name: "Toothbrush", quantity: "1", category: .hygiene),
            Item(id: UUID().uuidString, name: "Toothpaste", quantity: "1 Tube", category: .hygiene),
            Item(id: UUID().uuidString, name: "Toilet Paper", quantity: "1 Rolls", category: .hygiene),
            Item(id: UUID().uuidString, name: "Hairbrush", quantity: "1", category: .hygiene),
            Item(id: UUID().uuidString, name: "Hand Mirror", quantity: "1", category: .hygiene),
            Item(id: UUID().uuidString, name: "Towels", quantity: "3", category: .hygiene),
            Item(id: UUID().uuidString, name: "Disposable Razor", quantity: "2", category: .hygiene),
            Item(id: UUID().uuidString, name: "Contact Lenses", quantity: "4 Pairs", category: .hygiene),
            Item(id: UUID().uuidString, name: "Sunscreen", quantity: "1 Bottle", category: .hygiene),
            Item(id: UUID().uuidString, name: "Tissues", quantity: "1 Pack", category: .hygiene),
            Item(id: UUID().uuidString, name: "Cotton Swabs", quantity: "1 Box", category: .hygiene),
            
            Item(id: UUID().uuidString, name: "Bandages", quantity: "1 Pack", category: .firstAid),
            Item(id: UUID().uuidString, name: "Painkillers (Headache, Stomachache, etc.)", quantity: "1 Pack", category: .firstAid),
            Item(id: UUID().uuidString, name: "Insect Repellent", quantity: "1 Bottle", category: .firstAid),
            Item(id: UUID().uuidString, name: "Wound Ointment", quantity: "1 Tube", category: .firstAid),
            Item(id: UUID().uuidString, name: "After Sun Cream", quantity: "1 Tube", category: .firstAid),
            Item(id: UUID().uuidString, name: "Magnesium Tablets", quantity: "2 Tabs", category: .firstAid),
            Item(id: UUID().uuidString, name: "Disinfectant Spray", quantity: "1 Bottle", category: .firstAid),
            Item(id: UUID().uuidString, name: "Tick Remover", quantity: "1", category: .firstAid),
            
            Item(id: UUID().uuidString, name: "T-Shirts", quantity: "3", category: .clothing),
            Item(id: UUID().uuidString, name: "Sweaters", quantity: "1", category: .clothing),
            Item(id: UUID().uuidString, name: "Pants", quantity: "1", category: .clothing),
            Item(id: UUID().uuidString, name: "Jacket", quantity: "1", category: .clothing),
            Item(id: UUID().uuidString, name: "Shoes", quantity: "1 Pair", category: .clothing),
            Item(id: UUID().uuidString, name: "Underwear", quantity: "4 Pairs", category: .clothing),
            Item(id: UUID().uuidString, name: "Swimsuit", quantity: "1", category: .clothing),
            Item(id: UUID().uuidString, name: "Rain Poncho", quantity: "1", category: .clothing),
            Item(id: UUID().uuidString, name: "Comfortable Clothes", quantity: "1 Set", category: .clothing),
            Item(id: UUID().uuidString, name: "Pajamas", quantity: "1 Set", category: .clothing),
            Item(id: UUID().uuidString, name: "Socks", quantity: "4 Pairs", category: .clothing),
            
            Item(id: UUID().uuidString, name: "Water Bottle", quantity: "1", category: .equipment),
            Item(id: UUID().uuidString, name: "Backpack", quantity: "1", category: .equipment),
            Item(id: UUID().uuidString, name: "Earplugs", quantity: "1 Pair", category: .equipment),
            Item(id: UUID().uuidString, name: "Waist Pouch/Chest Bag", quantity: "1", category: .equipment),
            Item(id: UUID().uuidString, name: "Tent", quantity: "1", category: .equipment),
            Item(id: UUID().uuidString, name: "Camping Chair", quantity: "1", category: .equipment),
            Item(id: UUID().uuidString, name: "Flashlight", quantity: "1", category: .equipment),
            Item(id: UUID().uuidString, name: "Batteries", quantity: "2", category: .equipment),
            Item(id: UUID().uuidString, name: "Tarp", quantity: "1", category: .equipment),
            Item(id: UUID().uuidString, name: "Tent Pegs", quantity: "8", category: .equipment),
            Item(id: UUID().uuidString, name: "Rubber Mallet", quantity: "1", category: .equipment),
            Item(id: UUID().uuidString, name: "Sleeping Mat/Air Mattress", quantity: "1", category: .equipment),
            Item(id: UUID().uuidString, name: "Lighting", quantity: "1 set", category: .equipment),
            Item(id: UUID().uuidString, name: "Water Canister", quantity: "1", category: .equipment),
            Item(id: UUID().uuidString, name: "Gas Stove + Cartridge", quantity: "1", category: .equipment),
            Item(id: UUID().uuidString, name: "Cooking Pot", quantity: "1", category: .equipment),
            Item(id: UUID().uuidString, name: "Dishes", quantity: "1 set", category: .equipment),
            Item(id: UUID().uuidString, name: "Lighter/Matches", quantity: "1", category: .equipment),
            Item(id: UUID().uuidString, name: "Cooler Bag", quantity: "1", category: .equipment),
            Item(id: UUID().uuidString, name: "Dishwashing Liquid", quantity: "1 Bottle", category: .equipment),
            
            Item(id: UUID().uuidString, name: "Fruits (e.g., Apples)", quantity: "1", category: .food),
            Item(id: UUID().uuidString, name: "Canned Food", quantity: "3", category: .food),
            Item(id: UUID().uuidString, name: "Isotonic Tablets", quantity: "4", category: .food),
            Item(id: UUID().uuidString, name: "Spices", quantity: "1 Set", category: .food),
            Item(id: UUID().uuidString, name: "Instant Noodles", quantity: "2 Packs", category: .food),
            Item(id: UUID().uuidString, name: "Instant Coffee", quantity: "4 Sachets", category: .food),
            Item(id: UUID().uuidString, name: "Tea Bags", quantity: "4", category: .food),
            Item(id: UUID().uuidString, name: "Crackers", quantity: "1 Packs", category: .food),
            Item(id: UUID().uuidString, name: "Sugar/Coffee Whitener", quantity: "1 Pack", category: .food),
            Item(id: UUID().uuidString, name: "Soup Packets", quantity: "2 Packs", category: .food),
            
            Item(id: UUID().uuidString, name: "ID Card/Passport", quantity: "1", category: .documents),
            Item(id: UUID().uuidString, name: "Festival Tickets", quantity: "1", category: .documents),
            Item(id: UUID().uuidString, name: "Travel Insurance", quantity: "1", category: .documents),
            Item(id: UUID().uuidString, name: "Cash", quantity: "", category: .documents),
            Item(id: UUID().uuidString, name: "Health Insurance Card", quantity: "1", category: .documents),
            Item(id: UUID().uuidString, name: "Driver's License", quantity: "1", category: .documents),
            Item(id: UUID().uuidString, name: "Directions", quantity: "1 Copy", category: .documents),
            
            Item(id: UUID().uuidString, name: "Charging Cable", quantity: "1", category: .others),
            Item(id: UUID().uuidString, name: "Power Bank", quantity: "1", category: .others),
            Item(id: UUID().uuidString, name: "Clothesline", quantity: "1", category: .others),
            Item(id: UUID().uuidString, name: "Air Pump", quantity: "1", category: .others),
            Item(id: UUID().uuidString, name: "Radio/Speakers", quantity: "1", category: .others),
            Item(id: UUID().uuidString, name: "Toolkit", quantity: "1", category: .others),
            Item(id: UUID().uuidString, name: "Notebook and Pen", quantity: "1 Set", category: .others),
            Item(id: UUID().uuidString, name: "Duct Tape", quantity: "1 Roll", category: .others),
            Item(id: UUID().uuidString, name: "Cable Ties", quantity: "5", category: .others),
            Item(id: UUID().uuidString, name: "Blankets", quantity: "2", category: .others),
            Item(id: UUID().uuidString, name: "Sewing Kit", quantity: "1", category: .others)
        ],
        7: [
            Item(id: UUID().uuidString, name: "Shampoo", quantity: "1 Bottle", category: .hygiene),
            Item(id: UUID().uuidString, name: "Deodorant Spray", quantity: "1 Can", category: .hygiene),
            Item(id: UUID().uuidString, name: "Toothbrush", quantity: "1", category: .hygiene),
            Item(id: UUID().uuidString, name: "Toothpaste", quantity: "1 Tube", category: .hygiene),
            Item(id: UUID().uuidString, name: "Toilet Paper", quantity: "2 Rolls", category: .hygiene),
            Item(id: UUID().uuidString, name: "Hairbrush", quantity: "1", category: .hygiene),
            Item(id: UUID().uuidString, name: "Hand Mirror", quantity: "1", category: .hygiene),
            Item(id: UUID().uuidString, name: "Towels", quantity: "3", category: .hygiene),
            Item(id: UUID().uuidString, name: "Disposable Razor", quantity: "2", category: .hygiene),
            Item(id: UUID().uuidString, name: "Contact Lenses", quantity: "7 Pairs", category: .hygiene),
            Item(id: UUID().uuidString, name: "Sunscreen", quantity: "1 Bottle", category: .hygiene),
            Item(id: UUID().uuidString, name: "Tissues", quantity: "1 Pack", category: .hygiene),
            Item(id: UUID().uuidString, name: "Cotton Swabs", quantity: "1 Box", category: .hygiene),
            
            Item(id: UUID().uuidString, name: "Bandages", quantity: "1 Pack", category: .firstAid),
            Item(id: UUID().uuidString, name: "Painkillers (Headache, Stomachache, etc.)", quantity: "1 Pack", category: .firstAid),
            Item(id: UUID().uuidString, name: "Insect Repellent", quantity: "1 Bottle", category: .firstAid),
            Item(id: UUID().uuidString, name: "Wound Ointment", quantity: "1 Tube", category: .firstAid),
            Item(id: UUID().uuidString, name: "After Sun Cream", quantity: "1 Tube", category: .firstAid),
            Item(id: UUID().uuidString, name: "Magnesium Tablets", quantity: "7 Tabs", category: .firstAid),
            Item(id: UUID().uuidString, name: "Disinfectant Spray", quantity: "1 Bottle", category: .firstAid),
            Item(id: UUID().uuidString, name: "Tick Remover", quantity: "1", category: .firstAid),
            
            Item(id: UUID().uuidString, name: "T-Shirts", quantity: "5", category: .clothing),
            Item(id: UUID().uuidString, name: "Sweaters", quantity: "2", category: .clothing),
            Item(id: UUID().uuidString, name: "Pants", quantity: "3", category: .clothing),
            Item(id: UUID().uuidString, name: "Jacket", quantity: "1", category: .clothing),
            Item(id: UUID().uuidString, name: "Shoes", quantity: "1 Pair", category: .clothing),
            Item(id: UUID().uuidString, name: "Underwear", quantity: "7 Pairs", category: .clothing),
            Item(id: UUID().uuidString, name: "Swimsuit", quantity: "1", category: .clothing),
            Item(id: UUID().uuidString, name: "Rain Poncho", quantity: "1", category: .clothing),
            Item(id: UUID().uuidString, name: "Comfortable Clothes", quantity: "1 Set", category: .clothing),
            Item(id: UUID().uuidString, name: "Pajamas", quantity: "1 Set", category: .clothing),
            Item(id: UUID().uuidString, name: "Socks", quantity: "7 Pairs", category: .clothing),
            
            Item(id: UUID().uuidString, name: "Water Bottle", quantity: "1", category: .equipment),
            Item(id: UUID().uuidString, name: "Backpack", quantity: "1", category: .equipment),
            Item(id: UUID().uuidString, name: "Earplugs", quantity: "1 Pair", category: .equipment),
            Item(id: UUID().uuidString, name: "Waist Pouch/Chest Bag", quantity: "1", category: .equipment),
            Item(id: UUID().uuidString, name: "Tent", quantity: "1", category: .equipment),
            Item(id: UUID().uuidString, name: "Camping Chair", quantity: "1", category: .equipment),
            Item(id: UUID().uuidString, name: "Flashlight", quantity: "1", category: .equipment),
            Item(id: UUID().uuidString, name: "Batteries", quantity: "4", category: .equipment),
            Item(id: UUID().uuidString, name: "Tarp", quantity: "1", category: .equipment),
            Item(id: UUID().uuidString, name: "Tent Pegs", quantity: "8", category: .equipment),
            Item(id: UUID().uuidString, name: "Rubber Mallet", quantity: "1", category: .equipment),
            Item(id: UUID().uuidString, name: "Sleeping Mat/Air Mattress", quantity: "1", category: .equipment),
            Item(id: UUID().uuidString, name: "Lighting", quantity: "1 set", category: .equipment),
            Item(id: UUID().uuidString, name: "Water Canister", quantity: "1", category: .equipment),
            Item(id: UUID().uuidString, name: "Gas Stove + Cartridge", quantity: "1", category: .equipment),
            Item(id: UUID().uuidString, name: "Cooking Pot", quantity: "1", category: .equipment),
            Item(id: UUID().uuidString, name: "Dishes", quantity: "1 set", category: .equipment),
            Item(id: UUID().uuidString, name: "Lighter/Matches", quantity: "1", category: .equipment),
            Item(id: UUID().uuidString, name: "Cooler Bag", quantity: "1", category: .equipment),
            Item(id: UUID().uuidString, name: "Dishwashing Liquid", quantity: "1 Bottle", category: .equipment),
            
            Item(id: UUID().uuidString, name: "Fruits (e.g., Apples)", quantity: "3", category: .food),
            Item(id: UUID().uuidString, name: "Canned Food", quantity: "5", category: .food),
            Item(id: UUID().uuidString, name: "Isotonic Tablets", quantity: "7", category: .food),
            Item(id: UUID().uuidString, name: "Spices", quantity: "1 Set", category: .food),
            Item(id: UUID().uuidString, name: "Instant Noodles", quantity: "3 Packs", category: .food),
            Item(id: UUID().uuidString, name: "Instant Coffee", quantity: "7 Sachets", category: .food),
            Item(id: UUID().uuidString, name: "Tea Bags", quantity: "7", category: .food),
            Item(id: UUID().uuidString, name: "Crackers", quantity: "2 Packs", category: .food),
            Item(id: UUID().uuidString, name: "Sugar/Coffee Whitener", quantity: "1 Pack", category: .food),
            Item(id: UUID().uuidString, name: "Soup Packets", quantity: "2 Packs", category: .food),
            
            Item(id: UUID().uuidString, name: "ID Card/Passport", quantity: "1", category: .documents),
            Item(id: UUID().uuidString, name: "Festival Tickets", quantity: "1", category: .documents),
            Item(id: UUID().uuidString, name: "Travel Insurance", quantity: "1", category: .documents),
            Item(id: UUID().uuidString, name: "Cash", quantity: "", category: .documents),
            Item(id: UUID().uuidString, name: "Health Insurance Card", quantity: "1", category: .documents),
            Item(id: UUID().uuidString, name: "Driver's License", quantity: "1", category: .documents),
            Item(id: UUID().uuidString, name: "Directions", quantity: "1 Copy", category: .documents),
            
            Item(id: UUID().uuidString, name: "Charging Cable", quantity: "1", category: .others),
            Item(id: UUID().uuidString, name: "Power Bank", quantity: "1", category: .others),
            Item(id: UUID().uuidString, name: "Clothesline", quantity: "1", category: .others),
            Item(id: UUID().uuidString, name: "Air Pump", quantity: "1", category: .others),
            Item(id: UUID().uuidString, name: "Radio/Speakers", quantity: "1", category: .others),
            Item(id: UUID().uuidString, name: "Toolkit", quantity: "1", category: .others),
            Item(id: UUID().uuidString, name: "Notebook and Pen", quantity: "1 Set", category: .others),
            Item(id: UUID().uuidString, name: "Duct Tape", quantity: "1 Roll", category: .others),
            Item(id: UUID().uuidString, name: "Cable Ties", quantity: "5", category: .others),
            Item(id: UUID().uuidString, name: "Blankets", quantity: "2", category: .others),
            Item(id: UUID().uuidString, name: "Sewing Kit", quantity: "1", category: .others)
        ],
        14: [
            Item(id: UUID().uuidString, name: "Shampoo", quantity: "1 Bottle", category: .hygiene),
            Item(id: UUID().uuidString, name: "Deodorant Spray", quantity: "1 Can", category: .hygiene),
            Item(id: UUID().uuidString, name: "Toothbrush", quantity: "1", category: .hygiene),
            Item(id: UUID().uuidString, name: "Toothpaste", quantity: "1 Tube", category: .hygiene),
            Item(id: UUID().uuidString, name: "Toilet Paper", quantity: "3 Rolls", category: .hygiene),
            Item(id: UUID().uuidString, name: "Hairbrush", quantity: "1", category: .hygiene),
            Item(id: UUID().uuidString, name: "Hand Mirror", quantity: "1", category: .hygiene),
            Item(id: UUID().uuidString, name: "Towels", quantity: "3", category: .hygiene),
            Item(id: UUID().uuidString, name: "Disposable Razor", quantity: "2", category: .hygiene),
            Item(id: UUID().uuidString, name: "Contact Lenses", quantity: "14 Pairs", category: .hygiene),
            Item(id: UUID().uuidString, name: "Sunscreen", quantity: "1 Bottle", category: .hygiene),
            Item(id: UUID().uuidString, name: "Tissues", quantity: "3 Packs", category: .hygiene),
            Item(id: UUID().uuidString, name: "Cotton Swabs", quantity: "1 Box", category: .hygiene),
            
            Item(id: UUID().uuidString, name: "Bandages", quantity: "1 Pack", category: .firstAid),
            Item(id: UUID().uuidString, name: "Painkillers (Headache, Stomachache, etc.)", quantity: "1 Pack", category: .firstAid),
            Item(id: UUID().uuidString, name: "Insect Repellent", quantity: "1 Bottle", category: .firstAid),
            Item(id: UUID().uuidString, name: "Wound Ointment", quantity: "1 Tube", category: .firstAid),
            Item(id: UUID().uuidString, name: "After Sun Cream", quantity: "1 Tube", category: .firstAid),
            Item(id: UUID().uuidString, name: "Magnesium Tablets", quantity: "14 Tablets", category: .firstAid),
            Item(id: UUID().uuidString, name: "Disinfectant Spray", quantity: "1 Bottle", category: .firstAid),
            Item(id: UUID().uuidString, name: "Tick Remover", quantity: "1", category: .firstAid),
            
            Item(id: UUID().uuidString, name: "T-Shirts", quantity: "8", category: .clothing),
            Item(id: UUID().uuidString, name: "Sweaters", quantity: "3", category: .clothing),
            Item(id: UUID().uuidString, name: "Pants", quantity: "4", category: .clothing),
            Item(id: UUID().uuidString, name: "Jacket", quantity: "1", category: .clothing),
            Item(id: UUID().uuidString, name: "Shoes", quantity: "1 Pair", category: .clothing),
            Item(id: UUID().uuidString, name: "Underwear", quantity: "14 Pairs", category: .clothing),
            Item(id: UUID().uuidString, name: "Swimsuit", quantity: "1", category: .clothing),
            Item(id: UUID().uuidString, name: "Rain Poncho", quantity: "1", category: .clothing),
            Item(id: UUID().uuidString, name: "Comfortable Clothes", quantity: "1 Set", category: .clothing),
            Item(id: UUID().uuidString, name: "Pajamas", quantity: "1 Set", category: .clothing),
            Item(id: UUID().uuidString, name: "Socks", quantity: "14 Pairs", category: .clothing),
            
            Item(id: UUID().uuidString, name: "Water Bottle", quantity: "1", category: .equipment),
            Item(id: UUID().uuidString, name: "Backpack", quantity: "1", category: .equipment),
            Item(id: UUID().uuidString, name: "Earplugs", quantity: "1 Pair", category: .equipment),
            Item(id: UUID().uuidString, name: "Waist Pouch/Chest Bag", quantity: "1", category: .equipment),
            Item(id: UUID().uuidString, name: "Tent", quantity: "1", category: .equipment),
            Item(id: UUID().uuidString, name: "Camping Chair", quantity: "1", category: .equipment),
            Item(id: UUID().uuidString, name: "Flashlight", quantity: "1", category: .equipment),
            Item(id: UUID().uuidString, name: "Batteries", quantity: "4", category: .equipment),
            Item(id: UUID().uuidString, name: "Tarp", quantity: "1", category: .equipment),
            Item(id: UUID().uuidString, name: "Tent Pegs", quantity: "8", category: .equipment),
            Item(id: UUID().uuidString, name: "Rubber Mallet", quantity: "1", category: .equipment),
            Item(id: UUID().uuidString, name: "Sleeping Mat/Air Mattress", quantity: "1", category: .equipment),
            Item(id: UUID().uuidString, name: "Lighting", quantity: "1 Set", category: .equipment),
            Item(id: UUID().uuidString, name: "Water Canister", quantity: "1", category: .equipment),
            Item(id: UUID().uuidString, name: "Gas Stove + Cartridge", quantity: "1", category: .equipment),
            Item(id: UUID().uuidString, name: "Cooking Pot", quantity: "1", category: .equipment),
            Item(id: UUID().uuidString, name: "Dishes", quantity: "1 set", category: .equipment),
            Item(id: UUID().uuidString, name: "Lighter/Matches", quantity: "1", category: .equipment),
            Item(id: UUID().uuidString, name: "Cooler Bag", quantity: "1", category: .equipment),
            Item(id: UUID().uuidString, name: "Dishwashing Liquid", quantity: "1 Bottle", category: .equipment),
            
            Item(id: UUID().uuidString, name: "Fruits (e.g., Apples)", quantity: "7", category: .food),
            Item(id: UUID().uuidString, name: "Canned Food", quantity: "10", category: .food),
            Item(id: UUID().uuidString, name: "Isotonic Tablets", quantity: "14", category: .food),
            Item(id: UUID().uuidString, name: "Spices", quantity: "1 set", category: .food),
            Item(id: UUID().uuidString, name: "Instant Noodles", quantity: "7 Packs", category: .food),
            Item(id: UUID().uuidString, name: "Instant Coffee", quantity: "14 Sachets", category: .food),
            Item(id: UUID().uuidString, name: "Tea Bags", quantity: "14", category: .food),
            Item(id: UUID().uuidString, name: "Crackers", quantity: "4 Packs", category: .food),
            Item(id: UUID().uuidString, name: "Sugar/Coffee Whitener", quantity: "1 Pack", category: .food),
            Item(id: UUID().uuidString, name: "Soup Packets", quantity: "5 Packs", category: .food),
            
            Item(id: UUID().uuidString, name: "ID Card/Passport", quantity: "1", category: .documents),
            Item(id: UUID().uuidString, name: "Festival Tickets", quantity: "1", category: .documents),
            Item(id: UUID().uuidString, name: "Travel Insurance", quantity: "1", category: .documents),
            Item(id: UUID().uuidString, name: "Cash", quantity: "", category: .documents),
            Item(id: UUID().uuidString, name: "Health Insurance Card", quantity: "1", category: .documents),
            Item(id: UUID().uuidString, name: "Driver's License", quantity: "1", category: .documents),
            Item(id: UUID().uuidString, name: "Directions", quantity: "1 Copy", category: .documents),
            
            Item(id: UUID().uuidString, name: "Charging Cable", quantity: "1", category: .others),
            Item(id: UUID().uuidString, name: "Power Bank", quantity: "1", category: .others),
            Item(id: UUID().uuidString, name: "Clothesline", quantity: "1", category: .others),
            Item(id: UUID().uuidString, name: "Air Pump", quantity: "1", category: .others),
            Item(id: UUID().uuidString, name: "Radio/Speakers", quantity: "1", category: .others),
            Item(id: UUID().uuidString, name: "Toolkit", quantity: "1", category: .others),
            Item(id: UUID().uuidString, name: "Notebook and Pen", quantity: "1 Set", category: .others),
            Item(id: UUID().uuidString, name: "Duct Tape", quantity: "1 Roll", category: .others),
            Item(id: UUID().uuidString, name: "Cable Ties", quantity: "10", category: .others),
            Item(id: UUID().uuidString, name: "Blankets", quantity: "2", category: .others),
            Item(id: UUID().uuidString, name: "Sewing Kit", quantity: "1", category: .others)
        ]
    ]
}
